config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, reset_password

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('login/reset_password/', reset_password, name='reset_password'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {"blank": "True", "null": "True"}


class User(AbstractUser):
    username = None
    email = models.EmailField(
        verbose_name='Почта',
        unique=True)

    phone = models.CharField(
        max_length=35, verbose_name='Телефон',
        **NULLABLE, help_text='Введите номер телефона')

    avatar = models.ImageField(
        upload_to='users/avatars/', verbose_name='Аватар',
        **NULLABLE, help_text='Загрузите свой аватар')

    country = models.CharField(
        max_length=35, verbose_name='Страна',
        **NULLABLE, help_text='Введите страну')

    token = models.CharField(max_length=100, verbose_name='Token', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm

from catalog.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

users/views.py
import secrets
import random
import string

from django.core.mail import send_mail
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView

from config.settings import EMAIL_HOST_USER
from users.forms import UserRegisterForm
from users.models import User


class UserCreateView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/email-confirm/{token}/'
        send_mail(
            subject='Подтверждение почты',
            message=f'Перейди по ссылке для подтверждения почты {url}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email]
        )

        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))

def generate_password():
    password_characters = string.ascii_letters + string.digits + string.punctuation
    password = "".join(secrets.choice(password_characters) for _ in range(10))
    return password


def reset_password(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        user = get_object_or_404(User, email=email)
        password = generate_password()
        user.set_password(password)
        user.save()
        send_mail(
            subject='Восстановление пароля',
            message=f'Ваш пароль успешно изменен: {password}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        return redirect(reverse('users:login'))
    return render(request, 'reset_password.html')

users/templates/login.html
{% extends 'catalog/base.html' %}
{% block content %}

<form method='post' enctype="multipart/form-data">
    <div class="row">
        <div class="col-3">
        </div>

        <div class="col-6">
            <p class="card-text"> Пройдите регистрацию </p>
            <div class="card">

                <div class="card-body">

                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">
                        Войти
                    </button>
                    <a class="btn btn-primary" href="{% url 'users:reset_password' %}"
                       role="button">Восстановить пароль</a>

                </div>
            </div>
        </div>
    </div>

</form>

{% endblock %}

users/templates/reset_password.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="col-12">
    <div class="col-3"></div>
    <div class="col-3">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    Восстановление пароля
                </h3>
            </div>
            <div class="card-body">

                <form class="row" method="post">
                    {% csrf_token %}
                    <p class="card-text"> Введите вашу почту </p>
                    <input type="email" name="email">
                    <button type="submit" class="btn btn-primary">
                        Восстановить пароль
                    </button>
                </form>
            </div>
        </div>
    </div>

</div>

{% endblock %}