catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import ContactsView, BlogCreateView, BlogUpdateView, \
    BlogListview, BlogDetailview, BlogDeleteView, \
    ProductListview, ProductDetailview, ProductCreateView, ProductUpdateView, ProductDeleteView, \
    CategoryListView

app_name = CatalogConfig.name

urlpatterns = [
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('', ProductListview.as_view(), name='product_list'),
    path('category', CategoryListView.as_view(), name='category_list'),
    path('products/<int:pk>/', cache_page(60)(ProductDetailview.as_view()), name='product_detail'),
    path('products/create/', ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('blog/', BlogListview.as_view(), name='blog_list'),
    path('blog/<int:pk>/', BlogDetailview.as_view(), name='blog_detail'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/<int:pk>/update/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<int:pk>/delete/', BlogDeleteView.as_view(), name='blog_delete'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, reset_password

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('login/reset_password/', reset_password, name='reset_password'),
]

catalog/models.py
from django.db import models
from users.models import User

NULLABLE = {"blank": "True", "null": "True"}


class Product(models.Model):
    title = models.CharField(
        max_length=100,
        verbose_name="Наименование продукта",
        help_text="Введите название продукта",
    )

    desk = models.CharField(
        max_length=100,
        verbose_name="Описание продукта",
        help_text="Введите описание продукта",
    )

    image = models.ImageField(
        upload_to="media/photo",
        blank=True,
        null=True,
        verbose_name="Изображение(превью)",
        help_text="Загрузите изображение продукта",
    )

    category = models.ForeignKey(
        "Category",
        on_delete=models.SET_NULL,
        verbose_name="Категория",
        help_text="Введите Категорию продукта",
        null=True,
        blank=True,
        related_name="products",
    )

    price = models.IntegerField(
        blank=True,
        null=True,
        verbose_name="Цена за покупку",
        help_text="Введите Цену за покупку продукта",
    )

    created_at = models.DateField(
        blank=True,
        null=True,
        verbose_name="Дата создания(записи в БД)",
        help_text="Введите Дату создания продукта",
    )

    updated_at = models.DateField(
        blank=True,
        null=True,
        verbose_name="Дата последнего изменения(записи в БД)",
        help_text="Введите Дату последнего изменения продукта",
    )

    user = models.ForeignKey(
        User, on_delete=models.SET_NULL,
        verbose_name='Пользователь',
        help_text='Укажите владельца продукта', **NULLABLE
    )

    published = models.BooleanField(default=False, verbose_name='опубликован')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ["category", "title"]
        permissions = [
            ("can_canceled_public", "может отменять публикацию продукта"),
            ("can_edit_desk", "может менять описание продукта"),
            ("can_edit_category", "может менять категорию продукта")
        ]


class Category(models.Model):
    title = models.CharField(
        max_length=100,
        verbose_name="Наименование категории",
        help_text="Введите название категории",
    )

    desk = models.TextField(
        verbose_name="Описание категории", help_text="Введите описание категории"
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"


class Blog(models.Model):
    title = models.CharField(
        max_length=50,
        verbose_name="заголовок")
    slug = models.CharField(
        max_length=150,
        verbose_name="URL", **NULLABLE)
    content = models.TextField(
        verbose_name="содержимое", **NULLABLE)
    preview = models.ImageField(
        upload_to="media/photo", **NULLABLE)
    created_at = models.DateField(
        auto_created=True, verbose_name="дата создания")
    published = models.BooleanField(
        default=True, verbose_name="опубликован")
    views = models.IntegerField(
        default=0, verbose_name="количество просмотров")
    user = models.ForeignKey(User,
                             on_delete=models.SET_NULL, verbose_name='Пользователь',
                             help_text='Укажите владельца продукта', **NULLABLE
                             )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "блог"
        verbose_name_plural = "блоги"
        permissions = [
            ("can_edit", "может редактировать блог")
        ]


class Version(models.Model):
    product = models.ForeignKey(
        Product, related_name="Версия", verbose_name="Продукт",
        on_delete=models.CASCADE, **NULLABLE)

    version_num = models.IntegerField(
        verbose_name="Номер версии", **NULLABLE)

    version_title = models.CharField(
        max_length=100,
        verbose_name="Наименование продукта")

    current_version = models.BooleanField(default=True, verbose_name="Признак текущей версии")

    def __str__(self):
        return f"{self.product} {self.version_num} {self.version_title}"

    class Meta:
        verbose_name = "Версия"
        verbose_name_plural = "Версии"
        ordering = ["version_num", "product"]

catalog/forms.py
from django.forms import ModelForm, forms, BooleanField

from catalog.models import Product, Version, Blog


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fild_name, fild in self.fields.items():
            if isinstance(fild, BooleanField):
                fild.widget.attrs['class'] = "form-check-input"

            else:
                fild.widget.attrs['class'] = "form-control"




class ProductForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

        def clean_title(self):
            cleaned_data = self.cleaned_data.get('title')

            if cleaned_data in (
                    'казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар'):
                raise forms.ValidationError('Ошибка, связанная с вводом запрещенных слов')

            return cleaned_data


        def clean_desk(self):
            cleaned_data = self.cleaned_data.get('desk')

            if cleaned_data in (
                    'казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар'):
                raise forms.ValidationError('Ошибка, связанная с вводом запрещенных слов')

            return cleaned_data

class ProductModeratorForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Product
        fields = ("published", "desk", "category")


class VersionForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

class BlogForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Blog
        fields = '__all__'


class BlogModeratorForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Blog
        fields = ("title", "content", "published",)

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView
from pytils.translit import slugify
from catalog.forms import ProductForm, VersionForm, ProductModeratorForm, BlogForm, BlogModeratorForm
from catalog.models import Product, Blog, Version, Category
from catalog.services import get_product_from_cache, get_category_from_cache


# def home(request):
#     return render(request, 'home.html')


class ContactsView(TemplateView):
    template_name = 'catalog/contacts.html'

    def post(self, request):
        if request.method == 'POST':
            name = request.POST.get('name')
            phone = request.POST.get('phone')
            message = request.POST.get('message')

            print(f'You have new message from {name} ({phone}): {message}')
        return render(request, template_name='catalog/contacts.html')


class ProductListview(ListView):
    model = Product

    def get_queryset(self):
        return get_product_from_cache()

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        products = self.get_queryset(*args, **kwargs)

        for product in products:
            versions = Version.objects.filter(product=product)
            active_versions = versions.filter(current_version=True)
            if active_versions:
                product.active_version = active_versions.last().version_title
            else:
                product.active_version = 'Нет активной версии'

        context_data['object_list'] = products
        return context_data


class ProductDetailview(DetailView):
    model = Product


class ProductCreateView(CreateView, LoginRequiredMixin):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_list')

    def form_valid(self, form):
        product = form.save()
        user = self.request.user
        product.user = user
        product.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm

    def get_success_url(self):
        return reverse('catalog:product_detail', args=(self.kwargs.get('pk'),))

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        ProductFormset = inlineformset_factory(Product, Version, VersionForm, extra=1)

        if self.request.method == 'POST':
            context_data["formset"] = ProductFormset(self.request.POST, instance=self.object)
        else:
            context_data["formset"] = ProductFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data["formset"]

        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))

    def get_form_class(self):
        user = self.request.user
        if user == self.object.user:
            return ProductForm
        if user.has_perm(
            "catalog.can_canceled_public") and user.has_perm(
            "catalog.can_edit_desk") and user.has_perm(
            "catalog.can_edit_category"):
            return ProductModeratorForm

        raise PermissionDenied


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'catalog/product_delete.html'
    model = Product
    success_url = reverse_lazy('catalog:product_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner:
            self.object.view_counter += 1
            self.object.save()
            return self.object
        raise PermissionDenied()

class CategoryListView(ListView):
    model = Category

    def get_queryset(self):
        return get_category_from_cache()


class BlogListview(ListView):
    template_name = 'blog/blog_list.html'
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(published=True)
        return queryset


class BlogDetailview(DetailView):
    template_name = 'blog/blog_detail.html'
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views += 1
        self.object.save()
        return self.object


class BlogCreateView(CreateView):
    template_name = 'blog/blog_form.html'
    model = Blog
    fields = ('title', 'slug', 'content', 'preview', 'created_at')
    success_url = reverse_lazy('catalog:blog_list')

    def form_valid(self, form):
        if form.is_valid():
            new_art = form.save()
            new_art.slug = slugify(new_art.title)
            new_art.save()
        return super().form_valid(form)


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'blog/blog_form.html'
    model = Blog
    fields = ('title', 'slug', 'content', 'preview', 'created_at')

    def get_success_url(self):
        return reverse('catalog:blog_detail', args=(self.kwargs.get('pk'),))

    def get_form_class(self):
        user = self.request.user
        if user == self.object.user:
            return BlogForm
        if user.has_perm("catalog.can_edit"):
            return BlogModeratorForm
        raise PermissionDenied


class BlogDeleteView(DeleteView):
    template_name = 'blog/blog_delete.html'
    model = Blog
    success_url = reverse_lazy('catalog:blog_list')

catalog/templates/blog/blog_delete.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <div class="col">
                <form method="post">
                    {% csrf_token %}
                    <h1 class="fw-light">Вы уверены что хотите удалить?</h1>
                    <input type="submit" class="btn btn-primary" value="Да">
                    <a class="btn btn-primary" href="{% url 'catalog:blog_detail' blog.pk %}" role="button">Нет</a>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock  %}

catalog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <div class="col">
                <div class="card shadow-sm">
                    <img src="{{ object.preview | media_filter }}">
                    <div class="card-body">
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <p class="card-text">{{object.title}}</p>
                            <p class="card-text">{{object.content}}</p>
                            <p class="card-text">{{object.created_at}}</p>
                            <p class="card-text">{{object.views}} просмотров</p>
                        </ul>

                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'catalog:blog_list' %}"
                                   role="button">Назад</a>
                                {% if perms.blog.can_edit or user ==  blog.user %}
                                <a class="btn btn-primary" href="{% url 'catalog:blog_update' blog.pk %}"
                                   role="button">Редактировать</a>
                                <a class="btn btn-primary" href="{% url 'catalog:blog_delete' blog.pk %}"
                                   role="button">Удалить</a>
                                {% endif %}

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock  %}

catalog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method='post' enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">
                                {% if object %}
                                    Сохранить
                                {% else %}
                                    Создать
                                {% endif %}
                            </button>
                         </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}

<div class="album py-5 bg-body-tertiary">
    <section class="py-5 text-center container">

        <div class="col-lg-6 col-md-8 mx-auto">
            <a class="btn btn-primary" href="{% url 'catalog:product_list' %}" role="button">Назад</a>

            <a class="btn btn-primary" href="{% url 'catalog:blog_create' %}" role="button">Создать</a>
        </div>

    </section>
    <div class="container">

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for blog in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <img class="card-img-top" src="{{ blog.preview | media_filter }}">

                    <div class="card-body">
                        <p class="card-text">{{blog.title }}</p>
                        <p class="card-text">{{blog.content}}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'catalog:blog_detail' blog.pk %}"
                                   role="button">Посмотреть</a>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}