catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import ContactsView, BlogCreateView, BlogUpdateView, \
    BlogListview, BlogDetailview, BlogDeleteView, \
    ProductListview, ProductDetailview, ProductCreateView, ProductUpdateView, ProductDeleteView, \
    CategoryListView

app_name = CatalogConfig.name

urlpatterns = [
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('', ProductListview.as_view(), name='product_list'),
    path('category', CategoryListView.as_view(), name='category_list'),
    path('products/<int:pk>/', cache_page(60)(ProductDetailview.as_view()), name='product_detail'),
    path('products/create/', ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('blog/', BlogListview.as_view(), name='blog_list'),
    path('blog/<int:pk>/', BlogDetailview.as_view(), name='blog_detail'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/<int:pk>/update/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<int:pk>/delete/', BlogDeleteView.as_view(), name='blog_delete'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, reset_password

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('login/reset_password/', reset_password, name='reset_password'),
]

catalog/models.py
from django.db import models
from users.models import User

NULLABLE = {"blank": "True", "null": "True"}


class Product(models.Model):
    title = models.CharField(
        max_length=100,
        verbose_name="Наименование продукта",
        help_text="Введите название продукта",
    )

    desk = models.CharField(
        max_length=100,
        verbose_name="Описание продукта",
        help_text="Введите описание продукта",
    )

    image = models.ImageField(
        upload_to="media/photo",
        blank=True,
        null=True,
        verbose_name="Изображение(превью)",
        help_text="Загрузите изображение продукта",
    )

    category = models.ForeignKey(
        "Category",
        on_delete=models.SET_NULL,
        verbose_name="Категория",
        help_text="Введите Категорию продукта",
        null=True,
        blank=True,
        related_name="products",
    )

    price = models.IntegerField(
        blank=True,
        null=True,
        verbose_name="Цена за покупку",
        help_text="Введите Цену за покупку продукта",
    )

    created_at = models.DateField(
        blank=True,
        null=True,
        verbose_name="Дата создания(записи в БД)",
        help_text="Введите Дату создания продукта",
    )

    updated_at = models.DateField(
        blank=True,
        null=True,
        verbose_name="Дата последнего изменения(записи в БД)",
        help_text="Введите Дату последнего изменения продукта",
    )

    user = models.ForeignKey(
        User, on_delete=models.SET_NULL,
        verbose_name='Пользователь',
        help_text='Укажите владельца продукта', **NULLABLE
    )

    published = models.BooleanField(default=False, verbose_name='опубликован')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ["category", "title"]
        permissions = [
            ("can_canceled_public", "может отменять публикацию продукта"),
            ("can_edit_desk", "может менять описание продукта"),
            ("can_edit_category", "может менять категорию продукта")
        ]


class Category(models.Model):
    title = models.CharField(
        max_length=100,
        verbose_name="Наименование категории",
        help_text="Введите название категории",
    )

    desk = models.TextField(
        verbose_name="Описание категории", help_text="Введите описание категории"
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"


class Blog(models.Model):
    title = models.CharField(
        max_length=50,
        verbose_name="заголовок")
    slug = models.CharField(
        max_length=150,
        verbose_name="URL", **NULLABLE)
    content = models.TextField(
        verbose_name="содержимое", **NULLABLE)
    preview = models.ImageField(
        upload_to="media/photo", **NULLABLE)
    created_at = models.DateField(
        auto_created=True, verbose_name="дата создания")
    published = models.BooleanField(
        default=True, verbose_name="опубликован")
    views = models.IntegerField(
        default=0, verbose_name="количество просмотров")
    user = models.ForeignKey(User,
                             on_delete=models.SET_NULL, verbose_name='Пользователь',
                             help_text='Укажите владельца продукта', **NULLABLE
                             )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "блог"
        verbose_name_plural = "блоги"
        permissions = [
            ("can_edit", "может редактировать блог")
        ]


class Version(models.Model):
    product = models.ForeignKey(
        Product, related_name="Версия", verbose_name="Продукт",
        on_delete=models.CASCADE, **NULLABLE)

    version_num = models.IntegerField(
        verbose_name="Номер версии", **NULLABLE)

    version_title = models.CharField(
        max_length=100,
        verbose_name="Наименование продукта")

    current_version = models.BooleanField(default=True, verbose_name="Признак текущей версии")

    def __str__(self):
        return f"{self.product} {self.version_num} {self.version_title}"

    class Meta:
        verbose_name = "Версия"
        verbose_name_plural = "Версии"
        ordering = ["version_num", "product"]

catalog/forms.py
from django.forms import ModelForm, forms, BooleanField

from catalog.models import Product, Version, Blog


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fild_name, fild in self.fields.items():
            if isinstance(fild, BooleanField):
                fild.widget.attrs['class'] = "form-check-input"

            else:
                fild.widget.attrs['class'] = "form-control"




class ProductForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

        def clean_title(self):
            cleaned_data = self.cleaned_data.get('title')

            if cleaned_data in (
                    'казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар'):
                raise forms.ValidationError('Ошибка, связанная с вводом запрещенных слов')

            return cleaned_data


        def clean_desk(self):
            cleaned_data = self.cleaned_data.get('desk')

            if cleaned_data in (
                    'казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар'):
                raise forms.ValidationError('Ошибка, связанная с вводом запрещенных слов')

            return cleaned_data

class ProductModeratorForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Product
        fields = ("published", "desk", "category")


class VersionForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

class BlogForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Blog
        fields = '__all__'


class BlogModeratorForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Blog
        fields = ("title", "content", "published",)

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView
from pytils.translit import slugify
from catalog.forms import ProductForm, VersionForm, ProductModeratorForm, BlogForm, BlogModeratorForm
from catalog.models import Product, Blog, Version, Category
from catalog.services import get_product_from_cache, get_category_from_cache


# def home(request):
#     return render(request, 'home.html')


class ContactsView(TemplateView):
    template_name = 'catalog/contacts.html'

    def post(self, request):
        if request.method == 'POST':
            name = request.POST.get('name')
            phone = request.POST.get('phone')
            message = request.POST.get('message')

            print(f'You have new message from {name} ({phone}): {message}')
        return render(request, template_name='catalog/contacts.html')


class ProductListview(ListView):
    model = Product

    def get_queryset(self):
        return get_product_from_cache()

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        products = self.get_queryset(*args, **kwargs)

        for product in products:
            versions = Version.objects.filter(product=product)
            active_versions = versions.filter(current_version=True)
            if active_versions:
                product.active_version = active_versions.last().version_title
            else:
                product.active_version = 'Нет активной версии'

        context_data['object_list'] = products
        return context_data


class ProductDetailview(DetailView):
    model = Product


class ProductCreateView(CreateView, LoginRequiredMixin):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_list')

    def form_valid(self, form):
        product = form.save()
        user = self.request.user
        product.user = user
        product.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm

    def get_success_url(self):
        return reverse('catalog:product_detail', args=(self.kwargs.get('pk'),))

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        ProductFormset = inlineformset_factory(Product, Version, VersionForm, extra=1)

        if self.request.method == 'POST':
            context_data["formset"] = ProductFormset(self.request.POST, instance=self.object)
        else:
            context_data["formset"] = ProductFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data["formset"]

        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))

    def get_form_class(self):
        user = self.request.user
        if user == self.object.user:
            return ProductForm
        if user.has_perm(
            "catalog.can_canceled_public") and user.has_perm(
            "catalog.can_edit_desk") and user.has_perm(
            "catalog.can_edit_category"):
            return ProductModeratorForm

        raise PermissionDenied


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'catalog/product_delete.html'
    model = Product
    success_url = reverse_lazy('catalog:product_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner:
            self.object.view_counter += 1
            self.object.save()
            return self.object
        raise PermissionDenied()

class CategoryListView(ListView):
    model = Category

    def get_queryset(self):
        return get_category_from_cache()


class BlogListview(ListView):
    template_name = 'blog/blog_list.html'
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(published=True)
        return queryset


class BlogDetailview(DetailView):
    template_name = 'blog/blog_detail.html'
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views += 1
        self.object.save()
        return self.object


class BlogCreateView(CreateView):
    template_name = 'blog/blog_form.html'
    model = Blog
    fields = ('title', 'slug', 'content', 'preview', 'created_at')
    success_url = reverse_lazy('catalog:blog_list')

    def form_valid(self, form):
        if form.is_valid():
            new_art = form.save()
            new_art.slug = slugify(new_art.title)
            new_art.save()
        return super().form_valid(form)


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'blog/blog_form.html'
    model = Blog
    fields = ('title', 'slug', 'content', 'preview', 'created_at')

    def get_success_url(self):
        return reverse('catalog:blog_detail', args=(self.kwargs.get('pk'),))

    def get_form_class(self):
        user = self.request.user
        if user == self.object.user:
            return BlogForm
        if user.has_perm("catalog.can_edit"):
            return BlogModeratorForm
        raise PermissionDenied


class BlogDeleteView(DeleteView):
    template_name = 'blog/blog_delete.html'
    model = Blog
    success_url = reverse_lazy('catalog:blog_list')

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <script type="text/javascript"
            src="https://gc.kis.v2.scr.kaspersky-labs.com/FD126C42-EBFA-4E12-B309-BB3FDD723AC1/main.js?attr=Ykvs6R7dZ3QPm9v193O5T4pDphTgBPtzgLWSrd25sGgPMCFfdMPkR3IluQjLzoyfKGyxGcPoaD0iA6TprePHd9CR0uhZad1nVH_DGRQxMZY"
            charset="UTF-8"></script>
    <script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.122.0">
    <title>Album example · Bootstrap v5.3</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/album/">


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#712cf9">


    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }

        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }

        .product-image {
        width: 100%;
        height: 450px;
        object-fit: cover;
        }

        .b-example-divider {
          width: 100%;
          height: 3rem;
          background-color: rgba(0, 0, 0, .1);
          border: solid rgba(0, 0, 0, .15);
          border-width: 1px 0;
          box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
          flex-shrink: 0;
          width: 1.5rem;
          height: 100vh;
        }

        .bi {
          vertical-align: -.125em;
          fill: currentColor;
        }

        .nav-scroller {
          position: relative;
          z-index: 2;
          height: 2.75rem;
          overflow-y: hidden;
        }

        .nav-scroller .nav {
          display: flex;
          flex-wrap: nowrap;
          padding-bottom: 1rem;
          margin-top: -1px;
          overflow-x: auto;
          text-align: center;
          white-space: nowrap;
          -webkit-overflow-scrolling: touch;
        }

        .btn-bd-primary {
          --bd-violet-bg: #712cf9;
          --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

          --bs-btn-font-weight: 600;
          --bs-btn-color: var(--bs-white);
          --bs-btn-bg: var(--bd-violet-bg);
          --bs-btn-border-color: var(--bd-violet-bg);
          --bs-btn-hover-color: var(--bs-white);
          --bs-btn-hover-bg: #6528e0;
          --bs-btn-hover-border-color: #6528e0;
          --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
          --bs-btn-active-color: var(--bs-btn-hover-color);
          --bs-btn-active-bg: #5a23c8;
          --bs-btn-active-border-color: #5a23c8;
        }

        .bd-mode-toggle {
          z-index: 1500;
        }

        .bd-mode-toggle .dropdown-menu .active .bi {
          display: block !important;
        }

    </style>


</head>
<body>
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
</svg>

<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#sun-fill"></use>
                </svg>
                Light
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Dark
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#circle-half"></use>
                </svg>
                Auto
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>


<header data-bs-theme="dark">
    {% include 'catalog/includes/inc_menu.html' %}
</header>

<main>

    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">ProdBerri</h1>
                <p class="lead text-body-secondary">ВКУСНЫЕ И СВЕЖИЕ ОВОЩИ И ФРУКТЫ <br/>ОСВЕЖАЮЩИЕ СОКИ И НАПИТКИ</p>
                <p>
                    <a href="{% url 'catalog:blog_list' %}" class="btn btn-primary my-2">Перейти на блог</a>
                    <a href="{% url 'catalog:category_list' %}" class="btn btn-primary my-2">Перейти в категории</a>
                </p>
            </div>
        </div>
    </section>


    {% block content %}
    {% endblock %}
</main>

<footer class="text-body-secondary py-5">
    <div class="container">
        <p class="float-end mb-1">
            <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
            <a class="p-2 btn btn-outline-primary" href="#">Back to top</a>


        </p>
        <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
        <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a
                href="/docs/5.3/getting-started/introduction/">getting started guide</a>.</p>
    </div>
</footer>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Категории</h1>
    <p class="lead">Категории - список доступных категорий для продуктов</p>
</div>

<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-4 mt-3">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-header">{{ object }}</h4>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}l>

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <div class="col">
                <div class="card shadow-sm">
                    <img class="card-img-top" src="{{ product.image|media_filter  }}">
                    <div class="card-body">
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <p class="card-text">{{object.title}}</p>
                            <p class="card-text">{{object.desk}}</p>
                            <p class="card-text">{{object.price}} рублей за шт/кг</p>
                            <p class="card-text">{{object.category}}</p>
                        </ul>

                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'catalog:product_list' %}"
                                   role="button">Назад</a>
                                {% if perms.catalog.can_canceled_public and perms.catalog.can_edit_desk and perms.catalog.can_edit_category or user == product.User %}
                                <a class="btn btn-primary" href="{% url 'catalog:product_update' product.pk %}"
                                   role="button">Редактировать</a>
                                <a class="btn btn-primary" href="{% url 'catalog:product_delete' product.pk %}"
                                   role="button">Удалить</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock  %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        {% if user.is_authenticated %}
        <a class="btn btn-primary" href="{% url 'catalog:product_create' %}" role="button">Создать</a>
        {% endif %}
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for product in object_list %}
            <div class="col d-flex align-items-stretch">
                <div class="card shadow-sm">
                    <img class="card-img-top" src="{{ product.image|media_filter  }}">
                    <div class="card-body">
                        <p class="card-text">{{ product.title }}</p>
                        <p class="card-text">{{ product.desk|slice:100 }}</p>
                        <p class="card-text">{{product.name}}</p>
                        <p>Активная версия: {{ product.active_version }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'catalog:product_detail' product.pk %}"
                                   role="button">Посмотреть</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock  %}